
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Auto-generate sidebar from docs directory
    },
  ],
};

export default sidebars;module.exports = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Auto-generate sidebar from docs.path
    },
  ],
};