import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for AI Book
  aiBookSidebar: [
    {
      type: 'category',
      label: 'AI Book: Physical AI & Humanoid Robotics',
      items: [
        'AI_BOOK/Introduction-Physical-AI',
        'AI_BOOK/Basics-Humanoid-Robotics',
        'AI_BOOK/ROS2-Fundamentals',
        'AI_BOOK/Digital-Twin-Simulation',
        'AI_BOOK/AI-in-Robotics-Applications',
        'AI_BOOK/Future-Trends-in-Physical-AI'
      ],
    },
  ],
};

export default sidebars;
