// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // assumes docs/intro.md exists
    },
    {
      type: 'category',
      label: 'Setup',
      items: [
        {
          type: 'doc',
          id: 'setup/workstation', // assumes docs/setup/workstation.md exists
        },
        {
          type: 'doc',
          id: 'setup/ros2', // assumes docs/setup/ros2.md exists
        },
        {
          type: 'doc',
          id: 'setup/simulation', // assumes docs/setup/simulation.md exists
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 1: Introduction to Physical AI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week1',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 2: ROS 2 Fundamentals',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week2',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 3: Digital Twin Simulation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week3',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 4: AI in Robotics Applications',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week4',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 5: Basics of Humanoid Robotics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week5',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 6: Control Systems',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week6',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 7: Perception Systems',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week7',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 8: Navigation & Path Planning',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week8',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 9: Manipulation & Grasping',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week9',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 10: Learning in Robotics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week10',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 11: Human-Robot Interaction',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week11',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 12: Integration & Testing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week12',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Week 13: Capstone Project',
      items: [
        {
          type: 'autogenerated',
          dirName: 'week13',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'References',
      items: [
        {
          type: 'doc',
          id: 'references/glossary',
        },
        {
          type: 'doc',
          id: 'references/resources',
        },
      ],
      collapsed: true,
    },
  ],
};

module.exports = sidebars;