
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aiBookSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Point to the current directory (since docs path is AI_BOOK/chapters)
    },
  ],
};

export default sidebars;