
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aiBookSidebar: [
    {
      type: 'autogenerated',
      dirName: 'AI_BOOK',
    },
  ],
};

export default sidebars;