// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'AI_BOOK', // Auto-generate sidebar from docs/AI_BOOK directory
    },
  ],
};

module.exports = sidebars;